name: Benchmark PR

on:
  pull_request_target:
    types: 
      - labeled

jobs:
  benchmark:
    if: ${{ github.event.label.name == 'benchmark' }}
    uses: mweberxyz/fastify-workflows/.github/workflows/benchmark-pr.yml@feature/benchmark-pr
    with:
      node-versions: '[16,18,20]'
      benchmarks-dir: 'examples/benchmark'
      bench-duration: '10'

